JKLSHFJKL

diff --git a/.github/workflows/build-test-release.yml b/.github/workflows/build-test-release.yml
--- a/.github/workflows/build-test-release.yml
+++ b/.github/workflows/build-test-release.yml
@@ -81,12 +81,16 @@ jobs:
         build_dir=$(echo "${{ steps.strings.outputs.build-output-dir }}" | tr '\\' '/')
         cd $build_dir
         cpack -G ZIP
+        if [[ $? -ne 0 ]]; then
+          echo "cpack command failed"
+          exit 1
+        fi
+        ls -l
         zip_name=$(ls *.zip)
         echo "zip-name=$zip_name" >> $GITHUB_ENV
         echo "Zip file details:"
         file $zip_name
         unzip -t $zip_name
-
     - name: Upload Artifacts
       env:
         zip-name: ${{ env.zip-name }}
